export const MOCK_NOTES = [
  {
    id: "1",
    title: "DBMS Unit 3: Normalization & Transaction Management",
    subject: "DBMS",
    uploader: "Satvik Kumar",
    tags: ["SQL", "1NF", "2NF", "BNCF", "ACID", "Transactions"],
    upvotes: 142,
    comments: 24,
    fileType: "pdf",
    createdAt: "2 days ago",
  },
  {
    id: "2",
    title: "Operating Systems: Memory Management & Paging",
    subject: "OS",
    uploader: "Priya S",
    tags: ["Virtual Memory", "Paging", "Segmentation", "TLB"],
    upvotes: 98,
    comments: 15,
    fileType: "pdf",
    createdAt: "4 days ago",
  },
  {
    id: "3",
    title: "Computer Networks: TCP/IP Model vs OSI Model",
    subject: "CN",
    uploader: "Rahul M",
    tags: ["TCP", "UDP", "OSI", "Networking", "Layers"],
    upvotes: 85,
    comments: 8,
    fileType: "image",
    createdAt: "1 week ago",
  },
  {
    id: "4",
    title: "DSA: Dynamic Programming Cheat Sheet",
    subject: "DSA",
    uploader: "Satvik Kumar",
    tags: ["DP", "Algorithms", "Memoization", "Tabulation", "Graphs"],
    upvotes: 215,
    comments: 42,
    fileType: "pdf",
    createdAt: "2 weeks ago",
  },
  {
    id: "5",
    title: "Engineering Physics: Quantum Mechanics Notes",
    subject: "Physics",
    uploader: "Ananya K",
    tags: ["Quantum", "Schrodinger", "Wave Function", "Physics"],
    upvotes: 62,
    comments: 5,
    fileType: "pdf",
    createdAt: "3 weeks ago",
  },
];
